name: Java CI with Local Server

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-test-and-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare Mock File and Server
        run: |
          mkdir server_root
          head -c 1024 /dev/zero > server_root/my-local-file.txt
          cd server_root && python3 -m http.server 8080 &
          sleep 3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # --- Run Tests ---
      - name: Run Tests
        run: ./gradlew test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: build/reports/tests/test

      # --- Build Fat JAR (Shadow) ---
      - name: Build Fat JAR
        run: ./gradlew clean shadowJar

      - name: Upload Fat JAR
        uses: actions/upload-artifact@v4
        with:
          name: parallel-downloader-jar
          path: build/libs/*-all.jar
